### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by manishas** [Shippable/docs#120]
https://github.com/Shippable/pm/issues/8375

Please complete content for page at http://rcdocs1.shippable.com/reference/int-github/ 

Sample page: http://rcdocs1.shippable.com/reference/int-docker-hub/

**Comment by jatindogra** [comment]
Picking this up. Will assign myself after lock access is unblocked.

**Comment by jatindogra** [comment]
This is completed and verified http://rcdocs1.shippable.com/reference/int-github/
