### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by manishas** [Shippable/docs#125]
https://github.com/Shippable/pm/issues/8375

Please complete content for page at http://rcdocs1.shippable.com/reference/int-slack/ 

Sample page: http://rcdocs1.shippable.com/reference/int-docker-hub/

**Comment by jatindogra** [comment]
This is completed and verified http://rcdocs1.shippable.com/reference/int-slack/

**Comment by manishas** [comment]
@jatindogra this does not follow the structure of the sample page. All we needed were the sections from the sample page....

reopening.

**Comment by jatindogra** [comment]
Verified http://rcdocs1.shippable.com/reference/int-slack/
