### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by manishas** [Shippable/docs#127]
https://github.com/Shippable/pm/issues/8375

Please complete content for page at http://rcdocs1.shippable.com/reference/int-email/ 

Sample page: http://rcdocs1.shippable.com/reference/int-docker-hub/

**Comment by jatindogra** [comment]
This is done and verified http://rcdocs1.shippable.com/reference/int-email/

**Comment by manishas** [comment]
@jatindogra this does not follow the structure of the sample page. All we needed were the sections from the sample page....

reopening.

**Comment by jatindogra** [comment]
I have removed the tab, as we don't need to create integration for email.
