### ISSUE TITLE
IRC

### ISSUE THREAD

**Issue by manishas** [Shippable/docs#128]
https://github.com/Shippable/pm/issues/8375

Please complete content for page at http://rcdocs1.shippable.com/reference/int-irc/ 

Sample page: http://rcdocs1.shippable.com/reference/int-docker-hub/

**Comment by jatindogra** [comment]
This is done and verified http://rcdocs1.shippable.com/reference/int-irc/

**Comment by manishas** [comment]
@jatindogra this does not follow the structure of the sample page. All we needed were the sections from the sample page....

reopening.

**Comment by manishas** [comment]
Also, even assuming you did not follow the sample page structure, how is this verified? 


![image](https://cloud.githubusercontent.com/assets/2983749/25315138/6c543f8a-2805-11e7-92ed-7c4e350a97ed.png)

**Comment by manishas** [comment]
We need to be careful not to be sloppy with docs. This is the first touchpoint customers have with Shippable and they lose confidence in us if we cannot even write docs pages properly.

**Comment by jatindogra** [comment]
I have removed the tab, as we don't need to create integration for IRC
