### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by manishas** [Shippable/docs#131]
https://github.com/Shippable/pm/issues/8375

Please complete content for page at http://rcdocs1.shippable.com/reference/int-kubernetes/ 

Sample page: http://rcdocs1.shippable.com/reference/int-docker-hub/

**Comment by shubhankit92** [comment]
unassigning myself for jatin to pick this up.

**Comment by jatindogra** [comment]
Verified at http://rcdocs1.shippable.com/reference/int-kubernetes/
