### ISSUE TITLE
Unable to deploy , error getting service

### ISSUE THREAD

**Issue by iparraguezs** [Shippable/docs#1345]
Dears,
   I have a problem, to execute job deployment.
here is the shippable link.
https://app.shippable.com/bitbucket/mxitechnologies/jobs/lp-notify-deploy-test-integration-ecs/builds/5bc891aa64e8ed070007a421/console

**Comment by ric03uec** [comment]
closing this as it was resolved here: https://github.com/Shippable/support/issues/4610
