### ISSUE TITLE
Implement search functionality

### ISSUE THREAD

**Issue by manishas** [Shippable/docs#141]
https://github.com/Shippable/pm/issues/8376

Implement search functionality with a similar UX as https://segment.com/docs . As the user is typing, the search results in the dropdown should update and user can then click on any result to open the page.

If using Algolia, we can see if the search can return results like circleci search in docs

**Comment by ghost** [comment]
@manishas I have implemented the search functionality and have done some styling. You can check that out.

**Comment by ghost** [comment]
Un-assigning myself as my work is done as @ambarish2012 will take over from here.

**Comment by manishas** [comment]
this is done.
