### ISSUE TITLE
Add options to right pane for edit and support

### ISSUE THREAD

**Issue by manishas** [Shippable/docs#144]
https://github.com/Shippable/pm/issues/8378

Add 2 items to the pane just like Docker docs at https://docs.docker.com/engine/swarm/swarm-mode/

- **Edit this page** with a link to edit the page in the docs repo. For example, the edit this page link for the [Setting email](http://rcdocs1.shippable.com/getting-started/set-email/) page would be https://github.com/Shippable/docs/edit/master/sources/getting-started/set-email.md

- **Get help** with a link to creating a new support issue

**Comment by scriptnull** [comment]
Verified on rc docs. http://rcdocs1.shippable.com/
