### ISSUE TITLE
cliConfig

### ISSUE THREAD

**Issue by manishas** [Shippable/docs#158]
https://github.com/Shippable/pm/issues/8380

Update sources/reference/resource-cliConfig.md. Content can be the same as from the [old docs page for this resource](http://docs.shippable.com/pipelines/resources/cliConfig/).

Sample page is at sources/reference/resource-cluster.md

**Comment by sreyaj** [comment]
verified this in rc
http://rcdocs1.shippable.com/reference/resource-cliconfig/

(pr closed https://github.com/Shippable/docs/pull/188 here)
