### ISSUE TITLE
dockerOptions

### ISSUE THREAD

**Issue by manishas** [Shippable/docs#159]
https://github.com/Shippable/pm/issues/8380

Update sources/reference/resource-dockerOptions.md. Content can be the same as from the [old docs page for this resource](http://docs.shippable.com/pipelines/resources/dockerOptions/).

Sample page is at sources/reference/resource-cluster.md

**Comment by Varsha-Arun** [comment]
this is verified http://rcdocs1.shippable.com/reference/resource-dockeroptions/ 
hence closing
