### ISSUE TITLE
integration

### ISSUE THREAD

**Issue by manishas** [Shippable/docs#163]
https://github.com/Shippable/pm/issues/8380

Update sources/reference/resource-integration.md. Content can be the same as from the [old docs page for this resource](http://docs.shippable.com/pipelines/resources/integration/).

Sample page is at sources/reference/resource-cluster.md

**Comment by RevathiRD** [comment]
Verified in rc.
http://rcdocs1.shippable.com/reference/resource-integration/
hence closing.
