### ISSUE TITLE
loadbalancer

### ISSUE THREAD

**Issue by manishas** [Shippable/docs#164]
https://github.com/Shippable/pm/issues/8380

Update sources/reference/resource-loadbalancer.md. Content can be the same as from the [old docs page for this resource](http://docs.shippable.com/pipelines/resources/loadbalancer/).

Sample page is at sources/reference/resource-cluster.md

**Comment by Varsha-Arun** [comment]
this is verified http://rcdocs1.shippable.com/reference/resource-loadbalancer/
hence closing
