### ISSUE TITLE
notification

### ISSUE THREAD

**Issue by manishas** [Shippable/docs#165]
https://github.com/Shippable/pm/issues/8380

Update sources/reference/resource-notification.md. Content can be the same as from the [old docs page for this resource](http://docs.shippable.com/pipelines/resources/notification/).

Sample page is at sources/reference/resource-notification.md

**Comment by Varsha-Arun** [comment]
this is verified http://rcdocs1.shippable.com/reference/resource-notification/ 
hence closing
