### ISSUE TITLE
replicas

### ISSUE THREAD

**Issue by manishas** [Shippable/docs#167]
https://github.com/Shippable/pm/issues/8380

Update sources/reference/resource-replicas.md. Content can be the same as from the [old docs page for this resource](http://docs.shippable.com/pipelines/resources/replicas/).

Sample page is at sources/reference/resource-cluster.md

**Comment by RevathiRD** [comment]
Verified in RC.
http://rcdocs1.shippable.com/reference/resource-replicas/
Hence closing.
