### ISSUE TITLE
Fix swagger styling

### ISSUE THREAD

**Issue by scriptnull** [Shippable/docs#187]
https://github.com/Shippable/pm/issues/8379

**Comment by scriptnull** [comment]
Fixed green line and alignment issues.

#### Things remaining here
fix the button style 

![image](https://cloud.githubusercontent.com/assets/4211715/25313792/79f554c8-2853-11e7-9ca6-2eb875c803e5.png)

Fix padding of HTTP methods
![image](https://cloud.githubusercontent.com/assets/4211715/25313796/9d279a8c-2853-11e7-9d6a-d843f8bd8e25.png)

**Comment by scriptnull** [comment]
Unassigned to work on high priority issue.

**Comment by jatindogra** [comment]
Verified at http://localhost:5555/reference/api-overview/#/

**Comment by jatindogra** [comment]
Reopening this as some more work needs to be done.

**Comment by jatindogra** [comment]
Verified at http://rcdocs1.shippable.com/reference/api-overview/#/
