### ISSUE TITLE
Direct links to section URL should re-direct to default page

### ISSUE THREAD

**Issue by ttrahan** [Shippable/docs#423]
Currently, a 404 error is thrown if you directly navigate to a page URL like:
http://docs.shippable.com/reference

![image](https://user-images.githubusercontent.com/4467650/26855817-10985d6c-4ad2-11e7-98fd-6ad06b19c116.png)

We should re-direct automatically to a default page for each of these sections.

**Comment by ambarish2012** [comment]
Working on adding redirects.
