### ISSUE TITLE
Deploy master and newui branches in separate folders in RC

### ISSUE THREAD

**Issue by ambarish2012** [Shippable/docs#426]
The new ui branch documents interactions with the dashboard using the new UI. 
Requirements -

1) In RC, we want http://rcdocs1.shippable.com to point to the index.html of the new UI branch.
2) In RC we want http://rcdocs1.shippable.com/oldui to point to the index.html of the master branch.

**Comment by shrivara** [comment]
This is done with a different approach. http://rcdocs1.shippable.com serves the old one and http://rcdocs.shippable.com the new one.
