### ISSUE TITLE
8679.1 DOCS update docs saying that collaborators are not allowed to edit sub billing

### ISSUE THREAD

**Issue by deepikasl** [Shippable/docs#491]
https://github.com/Shippable/pm/issues/8679

**Comment by ric03uec** [comment]
- https://github.com/Shippable/pm/issues/8670

**Comment by deepikasl** [comment]
Verified
![screenshot from 2017-07-28 11 28 33](https://user-images.githubusercontent.com/18304961/28704386-e970867c-7387-11e7-9027-4e1f69e2b92e.png)
