### ISSUE TITLE
8738.2 - DOCS - Document `overwrite: true` for OUT steps

### ISSUE THREAD

**Issue by rageshkrishna** [Shippable/docs#512]
https://github.com/Shippable/pm/issues/8738

**Comment by brt-mlaccetti** [comment]
But what does `overwrite` *do*?!

**Comment by a-murphy** [comment]
If you're updating an `OUT` resource with a new key and value (for example, a new `versionName`), by default any other values already in the previous version of the resource will be copied to the new version.  With `overwrite`, the old values will not be copied and the new resource version will only have the new keys.  This would be useful if you are updating different keys in versions of the same resource and only want the most recently set keys and values to be present.
