### ISSUE TITLE
Demonstrate Shippable SaaS by Using it 

### ISSUE THREAD

**Issue by philoserf** [Shippable/docs#765]
Add shippable configuration to docs repository as demonstration of the platform. 

_I was really surprised that you hadn’t done this already._

**Comment by manishas** [comment]
:)

We do use Shippable to build docs... but the Assembly Lines for Shippable are centralized in the (poorly named) [beta repo](https://github.com/Shippable/beta). You'll see the `publish_rc_docs` and `publish_prod_docs` jobs in [shippable.jobs.yml](https://github.com/Shippable/beta/blob/master/shippable.jobs.yml) which call the script [deployDocs.sh](https://github.com/Shippable/beta/blob/master/deployDocs.sh).
