### ISSUE TITLE
document missing shipctl funcitons 

### ISSUE THREAD

**Issue by scriptnull** [Shippable/docs#865]
https://github.com/Shippable/pm/issues/9921

- get_resource_name
- get_resource_path
- get_params_resource
- copy_resource_file_from_state
- refresh_file_to_out_path
- get_resource_pointer_key

**Comment by manishas** [comment]
@scriptnull maybe I’m missing something but I removed these commands on purpose since we introduced better commands or they were not really necessary. 

Are any of these commands necessary? We shouldn’t document them just because we have them.

**Comment by manishas** [comment]
For example, we introduced http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/#copy_file_to_resource_state instead of copy_resource_file_to_state

**Comment by scriptnull** [comment]
Ok! Please note https://github.com/Shippable/docs/pull/866#issuecomment-360538874

Should we not add them at all? If we are sure that users won't need these, we could ignore my changes.

**Comment by scriptnull** [comment]
Verified on RC docs. http://rcdocs.shippable.com/platform/tutorial/workflow/using-shipctl
